version: "3.9"

services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes: 
      - ./backend:/usr/src/app
    depends_on:
      - mongodb
          
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5137:5137"
    volumes:
      - "./frontend:/usr/src/app"
    depends_on:
      - backend
